# BERT

# Preprocessing

In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

In [6]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [9]:
text_test = ['nice movie indeed' , 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

# Analysing preprocessed Text

In [12]:
text_preprocessed['input_mask']
#2 sentences so 2 masks
#CLS : In beginning  |   SEP : to separate sentences | 128 : max sentence length  

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [14]:
text_preprocessed['input_type_ids']
#useful when multiple sentences in one statement 

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [17]:
text_preprocessed['input_word_ids']
#unique ids for words

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

# Encoder

In [21]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'default', 'pooled_output', 'encoder_outputs'])

In [22]:
#pooled output is embeding for entire sentence
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411908,  0.49769565, ...,  0.24465255,
        -0.47334468,  0.81758696],
       [-0.9171231 , -0.47935167, -0.7865696 , ..., -0.6175173 ,
        -0.7102687 ,  0.92184293]], dtype=float32)>

In [24]:
#individual word embeding vector 2 for sentece, 128 for sentence size and padding, for each word 768 ize vector
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567834,  0.14476843, ..., -0.09677094,
          0.08722118,  0.07711093],
        [ 0.17839435, -0.19006091,  0.5034943 , ..., -0.05869817,
          0.32717112, -0.15578595],
        [ 0.18701491, -0.43388742, -0.4887515 , ..., -0.15502809,
          0.0014512 , -0.24470977],
        ...,
        [ 0.12083079,  0.12884267,  0.46453494, ...,  0.07375528,
          0.17441949,  0.16522124],
        [ 0.079679  , -0.01190603,  0.50225395, ...,  0.1377771 ,
          0.21002199,  0.00624612],
        [-0.072127  , -0.28303474,  0.59033364, ...,  0.4755191 ,
          0.1666846 , -0.08920307]],

       [[-0.07900569,  0.363351  , -0.21101557, ..., -0.17183766,
          0.16299717,  0.672427  ],
        [ 0.2788352 ,  0.4371633 , -0.35764715, ..., -0.04463672,
          0.3831512 ,  0.5887988 ],
        [ 1.2037673 ,  1.0727026 ,  0.48408794, ...,  0.24920954,
          0.4073093 ,  0.40481862],
        ...,

In [26]:
#output of each individua encoder
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901427,  0.00644757, -0.0361498 , ...,  0.04999618,
           0.06149192, -0.02657539],
         [ 1.1753384 ,  1.2140787 ,  1.1569978 , ...,  0.11634352,
          -0.35855362, -0.4049018 ],
         [ 0.03859034,  0.5386998 , -0.21089773, ...,  0.21858203,
           0.7260163 , -1.1158606 ],
         ...,
         [-0.07587028, -0.25421906,  0.7075512 , ...,  0.50541985,
          -0.18878683,  0.15028325],
         [-0.16066588, -0.28089684,  0.5759705 , ...,  0.5275854 ,
          -0.11141397,  0.02887545],
         [-0.04428164, -0.20279582,  0.5909355 , ...,  0.81338334,
          -0.39075816, -0.02601746]],
 
        [[ 0.18903586,  0.02752553, -0.06513736, ..., -0.00620207,
           0.15053885,  0.03165451],
         [ 0.5916148 ,  0.75891405, -0.07240671, ...,  0.6190398 ,
           0.8292891 ,  0.16161968],
         [ 1.4460825 ,  0.4460265 ,  0.4099028 , ...,  0.48255897,
           0.6269114 ,  0.13